#pragma once

/// \file
/// \brief Generic runtime response types shared by adapter-backed flows.

#include <cstdint>
#include <string>
#include <vector>

#include "inference/core/status.hpp"

namespace inference::runtime
{

/// \brief Generic runtime response returned by `ModelAdapter` implementations and `Session`.
struct Response
{
    /// Operation status for the request.
    core::Status         status = core::Status::Ok();
    /// Decoded text output when the runtime produces natural-language text.
    std::string          text;
    /// Optional token ids for the encoded prompt.
    std::vector<int32_t> prompt_token_ids;
    /// Optional token ids generated by decoder-style runtimes.
    std::vector<int32_t> generated_token_ids;
};

}  // namespace inference::runtime
